force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Guarantor__c.field-meta.xml
<CustomField>
    <fullName>Guarantor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guarantor</label>
    <referenceTo>Guarantor__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Guarantor__c/Guarantor__c.object-meta.xml
<CustomObject>
    <label>Guarantor</label>
    <nameField>
        <label>Guarantor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guarantors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Guarantor__c/fields/Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Number__c</fullName>
    <label>Contact Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guarantor__c/fields/isPrimary__c.field-meta.xml
<CustomField>
    <fullName>isPrimary__c</fullName>
    <label>isPrimary</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Guarantor__c/fields/Percent_of_guranty__c.field-meta.xml
<CustomField>
    <fullName>Percent_of_guranty__c</fullName>
    <label>Percent of guranty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Guarantor__c/fields/Relationship__c.field-meta.xml
<CustomField>
    <fullName>Relationship__c</fullName>
    <label>Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Brother</fullName>
            </value>
            <value>
                <fullName>Sister</fullName>
            </value>
            <value>
                <fullName>Friend</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/guarantorController.cls
public class guarantorController {

    public List<Guarantor__c> getGuarantors() {
        List<Guarantor__c> results = Database.query(
            'SELECT Id,Name, Contact_Number__c, isPrimary__c, Percent_of_guranty__c, Relationship__c FROM Guarantor__c'
        );
        return results;
    }
    
    public PageReference newGuarantor() {
        return Page.guarantor_new;
    }
    
    public PageReference step2() {
        return Page.asset_list;
    }
    
    public PageReference step3() {
        //return Page.gurantor_list;
        return null;
    }
    
    public Guarantor__c guarantor{ get; set; }
    public Application__c app;
    
    public GuarantorController(){
        
        Id guarantorId = ApexPages.currentPage().getParameters().get('guarantorId');
        guarantor= (guarantorId == null) ? new Guarantor__c() : 
            [SELECT Name, Contact_Number__c, isPrimary__c, Percent_of_guranty__c, Relationship__c FROM Guarantor__c WHERE Id = :guarantorId];
    
        Id appId= apexpages.currentpage().getparameters().get('applicationId');
        if(appId != Null){
            app = [SELECT Id, Name, Guarantor__c FROM Application__c WHERE Id = :appId];
        }
    }
    
    public Application__c getApp(){
        return app;
    }
    
    public PageReference updateApplication(){
        try{
            update app;
        }catch(System.DMLException e) {
            ApexPages.addMessages(e);
            return null;
        }
        
        PageReference myVFPage = new PageReference('/apex/application_summery');
        myVFPage.setRedirect(true);
        myVFPage.getParameters().put('applicationId', app.Id);
        return myVFPage;
    }
    
    public PageReference saveGuarantor() {
        try {
            upsert guarantor;
        } catch(System.DMLException e) {
            ApexPages.addMessages(e);
            return null;
        }
        return Page.guarantor_list;
    }
    
    public PageReference cancel() {
        return Page.guarantor_list;
    }
}