force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/App_Number__c.field-meta.xml
<CustomField>
    <fullName>App_Number__c</fullName>
    <displayFormat>A-{0000}</displayFormat>
    <label>App Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset_New__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Guarantor__c.field-meta.xml
<CustomField>
    <fullName>Guarantor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guarantor</label>
    <referenceTo>Guarantor__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Total_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Loan_Amount__c</fullName>
    <label>Total Loan Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Guarantor__c/Guarantor__c.object-meta.xml
<CustomObject>
    <label>Guarantor</label>
    <nameField>
        <label>Guarantor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guarantors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ApplicationController.cls
public class ApplicationController {
    
    public List<Application__c> getApplications() {
        List<Application__c> results = Database.query(
            'SELECT Id,Name, Address__c, App_Number__c, Asset__c, Contact__c, Guarantor__c, Total_Loan_Amount__c FROM Application__c'
        );
        return results;
    }
    
    public Application__c app { get; set; }
    public Application__c appSummery;
    
    public ApplicationController(){
        app = new Application__c();

        Id appId= apexpages.currentpage().getparameters().get('applicationId');
        if(appId != Null){
            appSummery = [SELECT Id, Name, Address__c, App_Number__c, Asset__c, Contact__c, Guarantor__c, Total_Loan_Amount__c  FROM Application__c WHERE Id = :appId];
        }
    }
    
    public Application__c getAppSummery(){
        return appSummery;
    }
    
    public PageReference newApplication(){
        return Page.application_new;
    }
    
    public PageReference saveApplication() { 
        try{
            insert app;
        }catch(System.DMLException e) {
            ApexPages.addMessages(e);
            return null;
        }
        PageReference myVFPage = new PageReference('/apex/asset_list');
        myVFPage.setRedirect(true);
        myVFPage.getParameters().put('applicationId', app.Id);
        return myVFPage;
    }
}