force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset_New__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_New__c/Asset_New__c.object-meta.xml
<CustomObject>
    <label>Asset_New</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets_New</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset_New__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssetController.cls
public class AssetController {

     public List<Asset_New__c> getAssets() {
        List<Asset_New__c> results = Database.query(
            'SELECT Id,Name, Model__c, Price__c, Year__c, Condition__c FROM Asset_New__c'
        );
        return results;
    }
    
    public PageReference newAsset() {
        return Page.asset_new;
    }
    
    public PageReference step1() {
        return Page.application_list;
    }
    
    public PageReference step2() {
        return Page.guarantor_list;
    }
    
    public Asset_New__c asset{ get; set; }
    public Application__c app;
    
    public AssetController(){
    
        Id assetId = ApexPages.currentPage().getParameters().get('assetId');
        asset= (assetId == null) ? new Asset_New__c() : 
            [SELECT Name, Model__c, Price__c, Year__c, Condition__c FROM Asset_New__c WHERE Id = :assetId];
    
        Id appId= apexpages.currentpage().getparameters().get('applicationId');
        if(appId != Null){
            app = [SELECT Id, Name, Asset__c FROM Application__c WHERE Id = :appId];
        } 
    }
    
    public Application__c getApp(){
        return app;
    }
    
    public PageReference updateApplication(){
        try{
            update app;
        }catch(System.DMLException e) {
            ApexPages.addMessages(e);
            return null;
        }
        
        PageReference myVFPage = new PageReference('/apex/guarantor_list');
        myVFPage.setRedirect(true);
        myVFPage.getParameters().put('applicationId', app.Id);
        return myVFPage;
    }
    
    
    
     public PageReference saveAsset() {
        try {
            upsert asset;
        } catch(System.DMLException e) {
            ApexPages.addMessages(e);
            return null;
        }
        
        return Page.asset_list;
    }
    
    public PageReference cancel(){
        return Page.asset_list;
    }
}